name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Restart Docker
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          yes | docker image prune
          docker build . -f docker/api/Dockerfile --no-cache -t api
          docker stop api-mutants
          docker rm api-mutants
            docker run \
               -e DB_HOST=$DB_HOST \
               -e DB_PORT=$DB_PORT \
               -e DB_USER=$DB_USER \
               -e DB_PASS=$DB_PASS \
               -e DB_NAME=$DB_NAME \
               -d -p 8090:8090 --name api-mutants api